apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernetes-deployment-tracer
rules:
- apiGroups: ['apps']
  resources: ['deployments']
  verbs: ['get', 'list', 'watch']
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-deployment-tracer
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-deployment-tracer
subjects:
- kind: ServiceAccount
  name: kubernetes-deployment-tracer
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: kubernetes-deployment-tracer
  apiGroup: rbac.authorization.k8s.io